name: Expo Publish
on:
  push:
    tags:
      - v*
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm ci
      - run: npm test
      - run: sed -i 's/{{AD_UNIT_ID_IOS}}/${{ secrets.AD_UNIT_ID_IOS_OUTSIDE }}/g' app.json
      - run: sed -i 's/{{AD_UNIT_ID_ANDROID}}/${{ secrets.AD_UNIT_ID_ANDROID_OUTSIDE }}/g' app.json
      - run: sed -i 's/{{AD_UNIT_ID_IOS}}/${{ secrets.AD_UNIT_ID_IOS_INSIDE }}/g' configs.json
      - run: sed -i 's/{{AD_UNIT_ID_ANDROID}}/${{ secrets.AD_UNIT_ID_ANDROID_INSIDE }}/g' configs.json
      - run: expo publish --release-channel prod
